## Types

***


## int

***

In [3]:
123

123

In [2]:
"123"

'123'

In [1]:
f"{13:08b}"

'00001101'

In [6]:
type(123.0)

float

In [7]:
type(123)

int

In [15]:
145*67

9715

In [16]:
type(145*67)

int

In [17]:
145-67

78

In [11]:
type(45-67)

int

In [18]:
145/67

2.1641791044776117

In [19]:
type(145/67)

float

In [21]:
145//67

2

In [20]:
type(145//67)

int

In [22]:
145%65

15

In [23]:
type(8/2)

float

In [24]:
type (8//2)

int

## numpy

***

In [25]:
import numpy as np

In [34]:
L = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=float)

In [35]:
print (L)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [36]:
L.dtype

dtype('float64')

In [38]:
Li = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [39]:
print (Li)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
Li.dtype

dtype('int32')

***

## End
